import { APIResource } from '../utility/common/api-resource';
import { Description } from '../utility/common/description';
import { FlavorText } from '../utility/common/flavor-text';
import { Name } from '../utility/common/name';
import { NamedAPIResource } from '../utility/common/named-api-resource';
import { Genus } from './genus';
import { PalParkEncounterArea } from './pal-park-encounter-area';
import { PokemonSpeciesDexEntry } from './pokemon-species-dex-entry';
import { PokemonSpeciesVariety } from './pokemon-species-variety';

export interface PokemonSpecies {
  id: number;
  name: string;
  order: number;
  gender_rate: number;
  capture_rate: number;
  base_happiness: number;
  is_baby: boolean;
  is_legendary: boolean;
  is_mythical: boolean;
  hatch_counter: number;
  has_gender_differences: boolean;
  forms_switchable: boolean;
  growth_rate: NamedAPIResource;
  pokedex_numbers: Array<PokemonSpeciesDexEntry>;
  egg_groups: Array<NamedAPIResource>;
  color: NamedAPIResource;
  shape: NamedAPIResource;
  evolves_from_species: NamedAPIResource;
  evolution_chain: APIResource;
  habitat: NamedAPIResource;
  generation: NamedAPIResource;
  names: Array<Name>;
  pal_park_encounters: Array<PalParkEncounterArea>;
  flavor_text_entries: Array<FlavorText>;
  form_descriptions: Array<Description>;
  genera: Array<Genus>;
  varieties: Array<PokemonSpeciesVariety>;
};
